I was a python beginner while doing this assignment, had no knowledge of algorithms and datastructures. Planning to revise after completing algorithms and datastructures.

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
def matrix_mul(A, B):
    """
    Get the product of two matrices
    :param A: list of list containing numbers
    :param B: list of list containing numbers
    :return: product of two matrices as list of list containing numbers
    """
    # if any of the matrices is empty
    if len(A) == 0 or len(B) == 0:
        print('Matrix should not be empty')

    # when no.of cols in 1st matrix equal to no. of rows in 2nd matrix
    try:

        # create ans matrix with zeroes equal to cols in second matrix and rows in first matrix
        _: int 
        ans = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

        # iterate through the rows of matrix A
        for i in range(len(A)):

            # iterate through the cols of matrix B
            for j in range(len(B[0])):

                # iterate through the rows of matrix B
                for k in range(len(B)):
                    ans[i][j] += A[i][k] * B[k][j]
        return ans

    except IndexError:
        print("No.of cols in 1st matrix must be equal to no. of rows in 2nd matrix")


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
# https://stackoverflow.com/questions/16489449/select-element-from-array-with-probability-proportional-to-its-value
from random import uniform


def pick_a_number_from_list(A):
    """
    selects an element from the list A randomly with probability proportional to its magnitude. 
     does the same experiment for 100 times with replacement, in each experiment prints a number 
     that is selected randomly from A.

    :param A: list of integers
    :return: dictionary with key value pair of number and its frequency
    """
    # if the list is empty
    if len(A) == 0:
        print('List should not be empty')

    # total all the values of list
    addition = sum(int(i) for i in A)

    # find proportion for all values in list
    prop_list = [int(i) / addition for i in A]
    total = 0

    # total of all proportional values
    cum_sum = []

    for j in range(len(prop_list)):
        total += prop_list[j]
        cum_sum.append(total)

    # random uniform value between 0 and 1
    r = uniform(0, 1)

    # if the random value is less than the value in cumulative sum of proportional values then return that cumsum value
    for i, k in enumerate(cum_sum):
        if r <= k:
            return i


def sampling_based_on_magnitude():
    sampl = {}

    for i in range(1, 100):

        # get the index value of a number which is greater than random value
        number = pick_a_number_from_list(A)

        # get the value based on index
        n = A[number]

        # if value not in dictionary add it
        if n not in sampl:
            sampl[n] = 1

        # if value is in dictionary , increment it by 1
        else:
            sampl[n] += 1
    print(sampl)


A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

pick_a_number_from_list(A)
sampling_based_on_magnitude()




{13: 3, 79: 20, 100: 28, 27: 11, 45: 23, 6: 3, 28: 9, 10: 2}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re


def replace_digits(String):
    """
    consider a string that will have digits in that,
    remove all the not digits and replace the digits with #

    :param String:string containing alphanumeric characters and symbols
    :return: string containing #s equals to number of digits in string
    """

    if len(String) == 0:
        print('Please provide the valid string')

    # Matches any character which is not a decimal digit
    pattern = re.compile('\D')

    # replace every occurrence of pattern with ''
    no_char = pattern.sub('', String)

    # Empty string to store result
    new_str = ''

    # replace numbers with # and add to empty string
    for _ in no_char:
        new_str += '#'
    return new_str


replace_digits('#2a$#b%c%561#')


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
# source:https://stackoverflow.com/questions/10695139/sort-a-list-of-tuples-by-2nd-item-integer-value

from icecream import ic


def display_dash_board(students, marks):
    """
    print the name of students a. Who got top 5 ranks, in the descending order of marks
    b. Who got least 5 ranks, in the increasing order of marks
    d. Who got marks between >25th percentile <75th percentile, in the increasing order of marks

    :param students: list of strings
    :param marks: list of numbers
    :return: students' name with marks in ascending order, descending order and between 25 to 75 percentile
    """
    # tuple of student and marks
    student_marks = list(zip(students, marks))
   

    # Sort the marks in ascending order
    sorted_asc_marks = (sorted(student_marks, key=lambda x: x[1]))

    # how many top or bottom students are there
    no = 5
    upto = 10

    print('-----------Top 5 Students-----------')

    # get stundents arranged with their marks in descending order
    for stu, mar in reversed(sorted_asc_marks[no:upto + 1]):
        print(stu, mar)

    print('-----------Bottom 5 Students---------')

    # get students arranged with their marks in ascending order
    for stu, mar in sorted_asc_marks[:no]:
        print(stu, mar)

    # percentile
    len_marks = len(marks)

    # First Quartile
    q_1 = 0.25

    # Third Quartile
    q_2 = 0.75

    # part 1
    p1 = int(q_1 * len_marks)
   

    # part2
    p2 = int(q_2 * len_marks)
    

    print('------Students in range 25% to 75%-------')

    for stu, mark in sorted_asc_marks[p1:p2]:
        print(stu, mark)


students = ['student1', 'student2', 'student3', 'student4', 'student5', 'student6', 'student7', 'student8', 'student9',
            'student10']
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(students, marks)


-----------Top 5 Students-----------
student8 98
student10 80
student2 78
student5 48
student7 47
-----------Bottom 5 Students---------
student3 12
student4 14
student9 35
student6 43
student1 45
------Students in range 25% to 75%-------
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
class Points(object):
    
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def numerator(self, other):
        """ calulates numerator for cosine_dist"""

        nume = (self.x * other.x) + (self.y * other.y)
        return nume

    def denominator(self, other):
        """ calculates denominator for cosine_dist"""

        denom = (((self.x ** 2 + self.y ** 2) ** 0.5) * ((other.x ** 2 + other.y ** 2) ** 0.5))
        if denom != 0:
            return denom
        else:
            print('Denom should not be zero')

    def cos_dist(self, other):
        """ calculates cosine distance"""
        dist = self.numerator(other) / self.denominator(other)
        return dist


def closest_points_to_p(S, P):
    """get closest points based on cosine distance"""

    # apply class object on Point P
    q = Points(P[0], P[1])

    cos_distance = []
    for i in range(len(S)):
        # apply class object on list of tuple
        p = Points(S[i][0], S[i][1])
        r = Points.cos_dist(p, q)

        # store all cosine distnaces
        cos_distance.append(r)

    # get indexes of all cosine distnace as key value pair    
    dist_indx = {x: i for i, x in enumerate(cos_distance)}

    # get indexes of values in list S as key value pair
    points_indx = {x: i for i, x in enumerate(S)}

    # sort distance items in reverse order
    dist_indx_desc = sorted(dist_indx.items(), reverse=True)

    n = []
    no = 5

    # get top5 closest points
    for k, v in dist_indx_desc[:no]:
        n.append(v)
    point_lst = [S[x] for x in n]
    return point_lst


S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
P = (3, -4)
closest_points_to_p(S, P)


[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import re

class Coordinate(object):
    
    def __init__(self,x,y):
        self.x = x
        self.y = y
        
    def eqn(self,other):
        intercept = 0
        e = ((self.x)*(other.x)) + ((self.y)*(other.y))
        return e + intercept


def i_am_the_one(red,blue,line):
    """
    Finds which line seperates red and blue points

    :param red: list of tuples(integers or floats)
    :param blue: list of tuples(integers or floats)
    :param line: list of equations (ax+by+c)
    :return:boolean to show which line separates red and blue and which doesn't
    """
    lines_x_y = []
    for i in line:
        signed_no = re.findall(r'[0-9\+\-\.]+',i)
       
        lines_x_y.append(signed_no)
    just_nums = [[float(x) for x in sublist] for sublist in lines_x_y]
    
    #get x and y values
    x_n_y = [(a,b) for [a,b,c] in just_nums]
  
    def side(list1):
        return(all(x > 0 for x in list1)) or (all(x<0 for x in list1))
    
    red_side = []
    blue_side= []
    for j in range(len(x_n_y)):
                
        # get x and y coordinates of the line
        d = Coordinate(x_n_y[j][0], x_n_y[j][1])
        
        
        # Get red points from all equations 
        red_points = []
        for i in range(len(red)):
            c = Coordinate(red[i][0], red[i][1])
            red_points.append(Coordinate.eqn(c,d))
         
        
        # Get Blue points from all equations
        blue_points = []
        for v in range(len(blue)):
            c = Coordinate(blue[v][0], blue[v][1])
            blue_points.append(Coordinate.eqn(c,d))

        
        
        # Are all points positive?
        i_am_r = side(red_points)
        red_side.append(i_am_r)
      

        # Are all points negative?
        i_am_b = side(blue_points)
        blue_side.append(i_am_b)

    ans = [a and b for a, b in zip(red_side, blue_side)]
    
    for w in ans:
        if w == True:
            print('YES')
        else:
            print('NO')
i_am_the_one([(1,1),(2,1),(4,2),(2,4),(-1,4)],[(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)],["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"])

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
def curve_smoothing(string):
    """
    Filling missing values
    :param string: string of numbers and blank spaces
    :return: string of numbers with avg of adjacent numbers
    
    """

    str_modified = string.split(',')

    # replace empty spaces with 0
    str_modified = [0 if x == '_' else x for x in str_modified]

    lst = list(map(int, str_modified))

    i = 0
    # when last and first elements of list are not zero(blank)
    if lst[0] != 0 and lst[-1] != 0:
        a = -1

    # when first element is not zero(empty) and last element is zero(blank)
    elif lst[0] != 0 and lst[-1] == 0:
        lst = lst[::-1]
        a = 0
    else:
        a = 0
    # when in between elements are zero(blank)
    while i < len(lst):

        # assign initial value of i , so that it can be used in else statement
        m = i

        # when element is nonzero element
        if lst[i] != 0:

            # assign the index to k
            k = i

            # calculate the value from adjacent values
            v = (lst[a] + lst[k]) / (k - a + 1)

            # assign calculated value to list
            for n in range(a, k + 1):
                lst[n] = v
            # assign latest k to a
            a = k
        # increment the index
        i += 1
    else:
        # when last element is zero
        if lst[-1] == 0:

            # calculates the value from adjacent values
            v = (lst[a] + lst[-1]) / (m - k + 1)

            # assign value to  the new list with modified values
            for n in range(a, m + 1):
                lst[n] = v
    return ','.join(map(str, lst))


s = "_,_,30,_,_,_,50,_,_"
curve_smoothing(s)


'10.0,10.0,12.0,12.0,12.0,12.0,4.0,4.0,4.0'

<h3> Q8: Compute conditional probabilities </h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
import re


def compute_conditional_probablities(A):
    """
    Computes conditional probabilities
    :param A: column of five unique values F1,F2,F3,F4,F5
    :return: conditional probabilities 
    """

    # create a list of unique f elements
    set_f = list(set([i[0] for i in A]))

    # create a list of unique s elements
    set_s = list(set([i[1] for i in A]))

    # create dictionary with s1, s2, s3 as keys and 0 as values
    dict_s = dict((el, 0) for el in set_s)

    # create combination of f elements and s elements
    comb_fs = []
    for i in set_f:
        for j in set_s:
            comb_fs.append(i + j)

    # combine elements from nested list
    comb_ele_a = [x + y for x, y in A]

    # combination of F and S as keys and 0 as values
    initial_dict = dict((el, 0) for el in comb_fs)

    for i in range(len(A)):
        if A[i][1] in dict_s:
            dict_s[A[i][1]] += 1

    for i in range(len(comb_ele_a)):
        if comb_ele_a[i] in initial_dict:
            initial_dict[comb_ele_a[i]] += 1
            
    for k,v in initial_dict.items():
        c = k[0:2]
        w = k[2:]
        a = int(v)/int(dict_s[w])
        ans = round(a,2)
     
        print('P(F={}/S=={})={}'.format(c,w,ans) )
    

   


A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'],
     ['F4', 'S3'], ['F5', 'S1']]

compute_conditional_probablities(A)


P(F=F4/S==S2)=0.0
P(F=F4/S==S3)=0.33
P(F=F4/S==S1)=0.25
P(F=F3/S==S2)=0.33
P(F=F3/S==S3)=0.33
P(F=F3/S==S1)=0.0
P(F=F2/S==S2)=0.33
P(F=F2/S==S3)=0.33
P(F=F2/S==S1)=0.25
P(F=F5/S==S2)=0.0
P(F=F5/S==S3)=0.0
P(F=F5/S==S1)=0.25
P(F=F1/S==S2)=0.33
P(F=F1/S==S3)=0.0
P(F=F1/S==S1)=0.25


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
def string_features(S1, S2):
    """
    given two sentances S1, S2 it finds
    a. Number of common words between S1, S2
    b. Words in S1 but not in S2
    c. Words in S2 but not in S1
    :param S1: string 1
    :param S2: string 2
    :return: integer, lists
    """
    s1 = S1.split()
    s2 = S2.split()
    count = 0
    m = []
    n = []
    for w in s1:
        if w in s2:
            count += 1

        if w not in s2:
            m.append(w)
    for w in s2:
        if w not in s1:
            n.append(w)
    return count, m, n


S1 = "the first column F will contain only 5 unique values"
S2 = "the second column S will contain only 3 unique values"
string_features(S1,S2)

(7, ['first', 'F', '5'], ['second', 'S', '3'])

<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
import math


def compute_log_loss(A):
    """
    Computes log loss
    :param A: nested list of classes and probabilities associated with classes
    :return: log loss
    """

    # Get probability values associated with class 1
    v1 = [x[1] for x in A if x[0] == 1]

    # Get probability values associated with class 0
    v0 = [x[1] for x in A if x[0] == 0]

    # deducting the probability value of class zero from 1
    v0_1 = [1 - x for x in v0]

    # probability values for belonging point to class 1
    vals = v1 + v0_1

    # log of probability values
    log_vals = [math.log10(x) for x in vals]

    # sum of log values
    tot_vals = math.fsum(log_vals)

    # calculation of logloss
    log_loss = -1*(tot_vals / len(A))
    return round(log_loss, 2)


A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)


0.42


In [11]:
from nose.tools import assert_equal, assert_raises

In [12]:
#https://stackoverflow.com/questions/11767938/how-to-use-noses-assert-raises
class TestPair(object):
    def test_matrix(self, sol):
        assert_equal(sol([[1, 2], [3, 4]], [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]), [[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]])
        assert_equal(sol([[1, 3, 4], [2, 5, 7], [5, 9, 6]], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]), [[1, 3, 4], [2, 5, 7], [5, 9, 6]])
        assert_raises(IndexError,sol([[1, 2], [3, 4]],[[1, 4], [5, 6], [7, 8], [9, 6]]))
        print('All Test Cases of matrix_mul Passed')
        
    def test_replace_digits(self, sol):
        assert_equal(sol("234"), "###")
        assert_equal(sol("a2b3c4"), "###")
        assert_equal(sol("abc"), "")
        assert_equal(sol("#2a$#b%c%561#"), "####")
        print('All Test Cases of replace_digits Passed')
        
    def test_closest_points_to_p(self, sol):
        assert_equal(sol([(1,2),(3,4),(-1,1),(6,-7),(0,6),(-5,-8),(-1,-1),(6,0),(1,-1)],(3,-4)), [(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)])
        print('All Test Cases of colsest_points_to_p passed')
        
    def test_curve_smoothing(self, sol):
        assert_equal(sol("_,_,_,24"), '6.0,6.0,6.0,6.0')
        assert_equal(sol("40,_,_,_,60"), '20.0,20.0,20.0,20.0,20.0')
        assert_equal(sol("80,_,_,_,_"), '16.0,16.0,16.0,16.0,16.0')
        assert_equal(sol("_,_,30,_,_,_,50,_,_"), '10.0,10.0,12.0,12.0,12.0,12.0,4.0,4.0,4.0')
        print('All Test Cases Of curve_smoothing Passed')

        
    def test_string_features(self, sol):
        S1 = "the first column F will contain only 5 unique values"
        S2 = "the second column S will contain only 3 unique values"
        assert_equal(sol(S1, S2), (7, ['first', 'F', '5'], ['second', 'S', '3']))
        print('All Test Cases of string_features passed')
        
    def test_compute_log_loss(self, sol):
        
        A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
        assert_equal(sol(A), 0.42)
        print('All Test Cases of compute_log_loss passed')        

        
t = TestPair()
t.test_matrix(matrix_mul)
t.test_replace_digits(replace_digits)
t.test_closest_points_to_p(closest_points_to_p)
t.test_curve_smoothing(curve_smoothing)
t.test_string_features(string_features)
t.test_compute_log_loss(compute_log_loss)
        

No.of cols in 1st matrix must be equal to no. of rows in 2nd matrix
All Test Cases of matrix_mul Passed
All Test Cases of replace_digits Passed
All Test Cases of colsest_points_to_p passed
All Test Cases Of curve_smoothing Passed
All Test Cases of string_features passed
All Test Cases of compute_log_loss passed


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: callable is None
  
